# Node.js
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'divija'
    sourceRepo: 'npm'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    workingFolder: '/1/s/npm-example'
