# Node.js
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: ArtifactoryGenericDownload@3
  inputs:
    connection: 'divija'
    specSource: 'file'
    file: 'npm-local/project-examples-master_npm-example_package.json'
    failNoOp: true
- task: ArtifactoryNpm@2
  inputs:
    command: 'install'
    artifactoryService: 'divija'
    sourceRepo: 'npm'
    collectBuildInfo: true
    threads: '1'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    workingFolder: 'npm-local/project-examples-master_npm-example_package.json'